name: Build Docker image and push to GitHub Package Registry
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: stretched/301/301
        username: stretched
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
